# Generated by Django 4.2.7 on 2024-01-23 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf', '0002_mergedpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compressed_file', models.FileField(upload_to='compressed_pdfs/')),
                ('compression_quality', models.CharField(choices=[('extreme', 'Extreme Compression - Less quality, high compression'), ('recommended', 'Recommended Compression - Good quality, good compression'), ('less', 'Less Compression - High quality, less compression')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
