# Generated by Django 4.2.7 on 2024-01-24 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf', '0005_pdfimageconversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordToPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_to_pdf', models.FileField(blank=True, null=True, upload_to='word_to_pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='WordToPdfConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_to_pdfs', models.ManyToManyField(related_name='word_to_pdfs', to='pdf.wordtopdf')),
            ],
        ),
    ]
