# Generated by Django 5.2.7 on 2025-10-23 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0010_ocrpdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFormatConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_format', models.CharField(choices=[('word', 'Word Document'), ('excel', 'Excel Spreadsheet'), ('powerpoint', 'PowerPoint'), ('jpeg', 'JPEG Images'), ('png', 'PNG Images'), ('text', 'Plain Text')], max_length=20)),
                ('converted_file', models.FileField(upload_to='pdf_conversions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
