# Generated by Django 4.2.7 on 2025-10-23 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf', '0011_pdfformatconversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatToPDFConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_format', models.CharField(choices=[('doc', 'DOC Document'), ('docx', 'DOCX Document'), ('txt', 'Text File'), ('rtf', 'RTF Document'), ('xls', 'XLS Spreadsheet'), ('xlsx', 'XLSX Spreadsheet'), ('csv', 'CSV File'), ('ppt', 'PPT Presentation'), ('pptx', 'PPTX Presentation'), ('jpg', 'JPEG Image'), ('jpeg', 'JPEG Image'), ('png', 'PNG Image'), ('gif', 'GIF Image'), ('bmp', 'BMP Image')], max_length=20)),
                ('converted_pdf', models.FileField(upload_to='format_to_pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
