# Generated by Django 4.2.7 on 2025-10-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0012_formattopdfconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrpdf',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('spa', 'Spanish'), ('fra', 'French'), ('deu', 'German')], default='eng', max_length=10),
        ),
        migrations.DeleteModel(
            name='FormatToPDFConversion',
        ),
    ]
