# Generated by Django 5.2.7 on 2025-11-11 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_summarizer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_length', models.IntegerField(default=60)),
                ('confidence_threshold', models.IntegerField(default=75)),
                ('key_facts', models.BooleanField(default=True)),
                ('legal_issues', models.BooleanField(default=True)),
                ('holdings_and_rulings', models.BooleanField(default=True)),
                ('recommendations', models.BooleanField(default=False)),
                ('citation_style', models.CharField(choices=[('bluebook', 'Bluebook'), ('apa', 'APA'), ('mla', 'MLA'), ('chicago', 'Chicago')], default='bluebook', max_length=20)),
                ('language', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German')], default='english', max_length=20)),
                ('auto_save', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
