# Generated by Django 4.2.7 on 2023-12-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscriptionplan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='free_trial', max_length=10, verbose_name='Subscription Duration'),
        ),
    ]
