# Generated by Django 4.2.7 on 2023-12-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_subscriptionplan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment ID'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Payment Status'),
        ),
    ]
