# Generated by Django 4.2.7 on 2025-10-01 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversations',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('total_pages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('start_char', models.IntegerField()),
                ('end_char', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.document')),
            ],
            options={
                'db_table': 'ai_document_chunks',
            },
        ),
        migrations.CreateModel(
            name='VectorEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='ai.documentchunk')),
            ],
            options={
                'db_table': 'ai_vector_embeddings',
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('query_mode', models.CharField(blank=True, max_length=50)),
                ('response_format', models.CharField(blank=True, max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.conversation')),
            ],
            options={
                'db_table': 'ai_conversation_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='ai_document_documen_1c72df_idx'),
        ),
    ]
