# Generated by Django 4.2.7 on 2025-10-06 16:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_judge_organization_remove_document_firm_name_case_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('citation', models.CharField(max_length=200, unique=True)),
                ('court', models.CharField(max_length=200)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('date_decided', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('pagerank_score', models.FloatField(default=0.0)),
                ('betweenness_score', models.FloatField(default=0.0)),
                ('citation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'court_cases',
                'indexes': [models.Index(fields=['citation'], name='court_cases_citatio_67cb8a_idx'), models.Index(fields=['court'], name='court_cases_court_ff99c1_idx'), models.Index(fields=['jurisdiction'], name='court_cases_jurisdi_ce99bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('citation_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('distinguished', 'Distinguished'), ('overruled', 'Overruled')], default='neutral', max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cited_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_received', to='ai.courtcase')),
                ('citing_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_made', to='ai.courtcase')),
            ],
            options={
                'db_table': 'citations',
                'indexes': [models.Index(fields=['citing_case'], name='citations_citing__c62972_idx'), models.Index(fields=['cited_case'], name='citations_cited_c_b63392_idx')],
                'unique_together': {('citing_case', 'cited_case')},
            },
        ),
    ]
